version: "3.3"
services:
   isammspringapp:
    container_name: isammspringapp
    build: ./
    volumes:
      - ./:/src
    environment:
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.url: jdbc:mysql://localhost:3306/ecommerceSpring?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
      spring.jpa.hibernate.ddl-auto: create
    links:
      - mysql
    depends_on:
      - mysql
    ports:
     - 8080:8080

   mysql:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: ecommerceSpring
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      TZ: Africa/Tunis
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     links:
       - mysql:mysql
     environment: 
       MYSQL_USERNAME: admin
       MYSQL_ROOT_PASSWORD: admin
       PMA_HOST: mysql
     ports:
       - 81:80